name: IBM Cloud Auto Restart 2

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 11 * * FRI'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        chmod -R 777 ./IBM_Cloud_CLI/
        ./IBM_Cloud_CLI/ibmcloud config --check-version=false
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT_2 }}
        REGION_NUM: ${{ secrets.REGION_NUM_2 }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        no
        EOF
    - name: Target IBM Cloud
      env:
        RESOURSE_ID: ${{ secrets.RESOURSE_ID_2 }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install -f -v 6.51.0
    - name: Restart IBM Cloud
      env:
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME_2 }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud cf restart "$IBM_APP_NAME"
